version: '3.9'
services:
    influxdb:
        image: influxdb:2.7.0
        volumes:
            - 'monitoring-influxdb:/var/lib/influxdb2'
        env_file:
            - ./.env
        networks:
            - monitoring
        configs:
            -   source: env_config
                target: /.env
    telegraf:
        image: telegraf:1.26.2
        configs:
            -   source: env_config
                target: /.env
            -   source: telegraf_config
                target: /etc/telegraf/telegraf.conf
        depends_on:
            - influxdb
        env_file:
            - ./.env
        networks:
            - traefik_traefik-public
            - monitoring
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 15s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=traefik_traefik-public"
                - "traefik.http.routers.telegraf.entrypoints=websecure"
                - "traefik.http.routers.telegraf.rule=Host(`telegraf.${DOMAIN:-localhost}`)"
                - "traefik.http.routers.telegraf.tls.certresolver=letsencryptresolver"
                - "traefik.http.services.telegraf.loadbalancer.server.port=8080"
    grafana:
        image: grafana/grafana-oss:latest
        depends_on:
            - influxdb
        volumes:
            - 'monitoring-grafana:/var/lib/grafana'
        environment:
            - "GF_AUTH_BASIC_ENABLED=true"
            - "GF_AUTH_DISABLE_LOGIN_FORM=true"
            - "GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=true"
            - "GF_AUTH_GENERIC_OAUTH_ENABLED=false"
            - "GF_AUTH_GENERIC_OAUTH_NAME=Keycloak"
            - "GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true"
            - "GF_AUTH_GENERIC_OAUTH_CLIENT_ID=${CLIENT_ID}"
            - "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=${CLIENT_SECRET}"
            - "GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME=email:primary"
            - "GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email"
            - "GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://${CLIENT_URL}/realms/${CLIENT_REALM}/protocol/openid-connect/auth"
            - "GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://${CLIENT_URL}/realms/${CLIENT_REALM}/protocol/openid-connect/token"
            - "GF_AUTH_GENERIC_OAUTH_API_URL=https://${CLIENT_URL}/realms/${CLIENT_REALM}/protocol/openid-connect/userinfo"
        env_file:
            - ./.env
        networks:
            - traefik_traefik-public
            - monitoring
        deploy:
            replicas: 1
            update_config:
                parallelism: 2 # обятельно 2 паралельных процесс
                delay: 15s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=traefik_traefik-public"
                - "traefik.http.routers.grafana.entrypoints=websecure"
                - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-localhost}`)"
                - "traefik.http.routers.grafana.tls.certresolver=letsencryptresolver"
                - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        configs:
            -   source: env_config
                target: /.env
            -   source: grafana_alerting_duplicati
                target: /etc/grafana/provisioning/alerting/duplicati_alert.yml
            -   source: grafana_alerting_email
                target: /etc/grafana/provisioning/alerting/email_contact_point.yml
            -   source: grafana_notifications_policies
                target: /etc/grafana/provisioning/alerting/notifications_policies.yml
            -   source: grafana_dashboard
                target: /etc/grafana/provisioning/dashboards/dashboards.yml
            -   source: grafana_dashboard_duplicati
                target: /etc/grafana/provisioning/dashboards/duplicati_dashboard.json
            -   source: grafana_datasource
                target: /etc/grafana/provisioning/datasources/datasources.yml
            -   source: grafana_notifiers
                target: /etc/grafana/provisioning/notifiers/notifiers.yml
networks:
    traefik_traefik-public:
        external: true
    monitoring:
        external: false
volumes:
    monitoring-influxdb:
    monitoring-grafana:

configs:
    env_config:
        file: ./.env
    telegraf_config:
        file: ./telegraf/telegraf.conf
    grafana_alerting_duplicati:
        file: ./grafana/provisioning/alerting/duplicati_alert.yml
    grafana_alerting_email:
        file: ./grafana/provisioning/alerting/email_contact_point.yml
    grafana_notifications_policies:
        file: ./grafana/provisioning/alerting/notifications_policies.yml
    grafana_dashboard:
        file: ./grafana/provisioning/dashboards/dashboards.yml
    grafana_dashboard_duplicati:
        file: ./grafana/provisioning/dashboards/duplicati_dashboard.json
    grafana_datasource:
        file: ./grafana/provisioning/datasources/datasources.yml
    grafana_notifiers:
        file: ./grafana/provisioning/notifiers/notifiers.yml
