version: '3.9'
services:
    influxdb:
        image: influxdb:2.7.0
        volumes:
            - 'monitoring-influxdb:/var/lib/influxdb2'
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=telegraf_user
            - DOCKER_INFLUXDB_INIT_PASSWORD=telegraf_password
            - DOCKER_INFLUXDB_INIT_ORG=telegraf_org
            - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=telegraf_token
            - DOCKER_INFLUXDB_INIT_RETENTION=
            - INFLUXD_REPORTING_DISABLED=false
            - TELEGRAF_LISTENER_PORT=8080
            - TELEGRAF_LISTENER_PATH=/
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=password
            - GF_SERVER_ROOT_URL=http://localhost:3000
            - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/duplicati_dashboard.json
            - GF_SMTP_ENABLED=false
            - GF_SMTP_HOST=localhost:25
            - GF_SMTP_FROM_NAME=Grafana
            - GF_SMTP_USER=
            - GF_SMTP_PASSWORD=
            - GF_SMTP_FROM_ADDRESS=admin@grafana.localhost
            - GF_SMTP_EHLO_IDENTITY=${HOSTNAME}
            - GF_SMTP_STARTTLS_POLICY=
            - NOTIFIER_EMAIL_RECIPIENT=example@example.com,example2@example.com
            - NOTIFIER_EMAIL_REMINDER_ENABLE=true
            - NOTIFIER_EMAIL_REMINDER_FREQUENCY=2h
        networks:
            - monitoring
    telegraf:
        image: telegraf:1.26.2
        configs:
            -   source: telegraf_config
                target: /etc/telegraf/telegraf.conf
        depends_on:
            - influxdb
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=telegraf_user
            - DOCKER_INFLUXDB_INIT_PASSWORD=telegraf_password
            - DOCKER_INFLUXDB_INIT_ORG=telegraf_org
            - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=telegraf_token
            - DOCKER_INFLUXDB_INIT_RETENTION=
            - INFLUXD_REPORTING_DISABLED=false
            - TELEGRAF_LISTENER_PORT=8080
            - TELEGRAF_LISTENER_PATH=/
        networks:
            - traefik_traefik-public
            - monitoring
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 15s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=traefik_traefik-public"
                - "traefik.http.routers.telegraf.entrypoints=websecure"
                - "traefik.http.routers.telegraf.rule=Host(`telegraf.${DOMAIN:-localhost}`)"
                - "traefik.http.routers.telegraf.tls.certresolver=letsencryptresolver"
                - "traefik.http.services.telegraf.loadbalancer.server.port=8080"
networks:
    traefik_traefik-public:
        external: true
    monitoring:
        external: false
volumes:
    monitoring-influxdb:

configs:
    telegraf_config:
        file: ./telegraf/telegraf.conf
